controller_manager:
  ros__parameters:

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    forward_gripper_position_controller:
      type: position_controllers/JointGroupPositionController

    robotiq_gripper_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster



joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 2.0
      $(var tf_prefix)shoulder_pan_joint: { trajectory: 1.0, goal: 1.0 }
      $(var tf_prefix)shoulder_lift_joint: { trajectory: 1.0, goal: 1.0 }
      $(var tf_prefix)elbow_joint: { trajectory: 1.0 , goal: 1.0 }
      $(var tf_prefix)wrist_1_joint: { trajectory: 1.0, goal: 1.0 }
      $(var tf_prefix)wrist_2_joint: { trajectory: 1.0, goal: 1.0 }
      $(var tf_prefix)wrist_3_joint: { trajectory: 1.0, goal: 1.0 }


forward_position_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint

forward_gripper_position_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)finger_joint


robotiq_gripper_joint_trajectory_controller:
  ros__parameters:
    joints:
     - $(var tf_prefix)finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      $(var tf_prefix)finger_joint: { trajectory: 0.5, goal: 0.1 }

robotiq_activation_controller:
  ros__parameters:
    default: true